# -*- coding: utf-8 -*-
"""inferance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iAjbOC_0Y8t2SafAmfKp29Dkrn-7T56q
"""

# main.py
from config import Config
from vectorizer import load_vectorizers
from model import load_model
from translate import translate

# Load the config, vectorizers, and model
config = Config()
eng_vectorizer, fra_vectorizer = load_vectorizers()
model = load_model()

# Example usage of the translate function
sentence = "Translate this English sentence to French."
translated_sentence = translate(sentence, config.sequence_length, config.target_vocab_size)
print("Translated sentence:", " ".join(translated_sentence))